site_name: Stack Project Docs
site_url: https://john-tech-writer.github.io/stack-project-docs

nav:
  - Home: index.md
  - Changelog: changelog.md
  - Orientation:
      - README: orientation.md
      - Directory Layout: directory-layout.md
      - Naming and Slugs: naming-slugs.md
      - Parking Lot: parking-lot.md
  - Content Production Workflow:
      - Volume Planning: volume-planning.md
      - Image Workflow: image-workflow.md
      - Image Lists: image-lists.md
      - Audio - Video Workflow: audio-video-workflow.md
      - Backup Workflow: backup-workflow.md
  - Publishing:
      - Substack Standards and Series: substack-standards-series.md
  - Templates:
      - Skeletons and Templates Workflow: skeletons-templates-workflow.md
theme:
  name: readthedocs

plugins:
  - search
  - mermaid2:
      javascript: https://unpkg.com/mermaid@10.4.0/dist/mermaid.esm.min.mjs

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid

extra_css:
  - stylesheets/extra.css
